### ISSUE TITLE
Feature request: Manually change Box and Slider radius

### ISSUE THREAD

**Issue by hmaesta** [jaames/iro.js#135]
**Box** and **Slider** radius is currently calculated by summing `padding` and `handleRadius`.

Would be nice to manually change this value to match the default border-radius of my design system.

https://github.com/jaames/iro.js/blob/25921cd190338887cc6403226dd30ee437c6f1bd/dist/iro.js#L967-L976

**Comment by jaames** [comment]
It's possible to do this with a bit of CSS:

```css
.IroSliderBg {
    rx: 0;
    ry: 0;
}

.IroBox rect {
    rx: 0;
    ry: 0;
}
```

But yeah, it'd be nice if there was a config option for this too. I'll look into it when I get the chance
