### ISSUE TITLE
How can i disable slider bar ?

### ISSUE THREAD

**Issue by thuyettiensinh** [jaames/iro.js#33]
I hope you can help.
I tried with a stupid way:  `g[0].innerHTML = '' ` in before `mount ` event.
Remove some element and it hidden but when I clicking on the white space (show it before) It still works as if nothing had happened.

**Comment by jaames** [comment]
A hacky workaround to this would be hiding the slider with CSS: 

```css
.iro__slider {
  display: none;
  visibility: hidden;
  pointer-events: none;
}
```

Then stop it from interacting with mouse clicks:

```js
colorPicker.on("mount", function(){
  colorPicker.ui.splice(1, 1);
});
```

Custom UI layouts are being planned for 4.0, though! The discussion for that is [here](https://github.com/jaames/iro.js/issues/30)
