### ISSUE TITLE
How to hide/reveal wheel ( slider callback interfere's)

### ISSUE THREAD

**Issue by ojazdowski** [jaames/iro.js#56]
Hi! Thanks for all you've done and achieved here. Great project and a great API! I'd like to have the option to hide and reveal the color wheel. I followed the FAQs and can now do both with CSS . I can hide it. I can reveal it. But if I hide the wheel and then move the slider the wheel is automatically revealed again ( must be overriding my css?) Any suggestions? Many Thanks

**Comment by jaames** [comment]
Hey! Thank you for the kind words!

You can hide the wheel with CSS by doing something like this -- the key is to force `display: none` with `!important`:

```css
.iro__wheel {
    visibility: hidden;
    pointer-events: none;
    display: none !important;
    height: 0;
}
```

I may consider some way to show/hide the color picker components from the API though. :)
